<?php
  
  $section_array = array(
    "010. Daily Section",
    "01. Daily Murli",
    "02. All Old Daily Murli - 2005-2020",
    "03. All Sakar Murli - 1963-1969",
    "04. All Avyakt Murli - 1969-2020",
    "-------------------------------------",
    "012. Daily Murli Sections",
    "01. Murli MahaVakya",
    "02. Murli Saar",
    "03. Murli Dharna",
    "04. Murli Vardans",
    "05. Murli Vardans - Hand",
    "06. Murli Slogans",
    "07. Murli Swamans",
    "08. Murli Chart",
    "09. Murli Point to Churn",
    "10. Murli GYDS",
    "11. Murli Crosswords",
    "12. Murli Quiz",
    "13. Murli Visual",
    "14. Murli Poems",
    "16. Murli Calendars",
    "17. Aaj Ka Purusharth",
    "18. Today Moti",
    "19. Dharmraj Ki Adalat",
    "21. Murli Saar Commentaries",
    "22. Murli Dharna Commentaries",
    "23. Murli Vardan Commentaries",
    "24. Murli Slogan Commentaries",
    "-------------------------------------",
    "013. Avyakt Murli Section",
    "01. All Avyakt Murli",
    "02. Avyakt Ishare",
    "03. Avyakt Murli Commentary",
    "04. Avyakt Murli Home Work",
    "05. Avyakt Murli MahaVakya",
    "06. Avyakt Murli Photos",
    "07. Avyakt Murli Quiz",
    "08. Avyakt Murli Revision",
    "09. Avyakt Palna",
    "10. Avyakt Sandesh",
    "11. Avyakt Signals - English",
    "12. BapDada Drills",
    "13. Celebrations",
    "14. Prabhu Milan",
    "-------------------------------------",
    "014. Avyakt Murli Project",
    "014. Avyakt Murli Project",
    "-------------------------------------",
    "016. Daily Meditation",
    "01. Daily Amritvela Meditation",
    "02. Daily Amritvela Meditation New",
    "03. Daily Divine Connect Meditation",
    "04. Daily Paramdham Meditation",
    "-------------------------------------",
    "017. Rajyoga Meditation",
    "01. Rajyoga Meditation",
    "02. Rajyoga Shibirs",
    "03. Rajyoga - Alchemy of God",
    "04. Yog Ki Vidhi",
    "05. Spiritual Powers",
    "-------------------------------------",
    "018. Meditation Commentaries",
    "01. Audio Meditation Commentaries",
    "02. Video Meditation Commentaries",
    "03. Guided Meditation",
    "04. Drills",
    "05. Commentaries - Pdf",
    "-------------------------------------",
    "019. Meditation Music",
    "01. Meditation Music",
    "02. Meditation Relaxing Music",
    "03. Rajyoga Meditation Music",
    "04. Background Music",
    "05. Instrumental Music",
    "06. Other Music",
    "-------------------------------------",
    "021. Seven days Course",
    "01. Seven Days Course - Htm",
    "02. Seven Days Course - Pdf",
    "03. Seven Days Course - Images",
    "04. Seven Days Course - Ppts",
    "05. Seven Days Course - Mp3",
    "06. Seven Days Course - Mp4",
    "07. Seven Days Course - Shibir",
    "-------------------------------------",
    "022. Amritvela",
    "01. Amritvela Series",
    "02. Amritvela Pdf",
    "03. Amritvela Commentaries",
    "-------------------------------------",
    "023. Panch Swaroop Ka Abhyas",
    "01. 5 Swaroop Ka Abhyas - Mp3",
    "02. 5 Swaroop Ka Abhyas - Mp4",
    "03. 5 Swaroop Ka Abhyas - Jpg",
    "-------------------------------------",
    "024. Char Dham",
    "01. Char Dham Tour - Mp4",
    "02. Char Dham Commentaries",
    "03. Char Dham Drills - Pdf",
    "-------------------------------------",
    "025. Bhagavad Gita",
    "025. Bhagavad Gita",
    "-------------------------------------",
    "026. Values and Education",
    "01. Values",
    "02. Value Education",
    "03. Virtues",
    "04. Self Respect",
    "05. Baba Praise",
    "06. Master Titles",
    "07. Companion of God",
    "08. 365 Days Wisdom",
    "-------------------------------------",
    "031. Classes",
    "01. Monthly Classes",
    "02. Double Foreigners Classes",
    "03. Other Classes",
    "-------------------------------------",
    "032. Baba Milan Classes",
    "01. Baba Milan Dates",
    "02. Baba Milan Classes",
    "03. Baba Milan Photos",
    "-------------------------------------",
    "033. Bhatti Classes",
    "033. Bhatti Classes",
    "-------------------------------------",
    "034. Bhog Messages",
    "034. Bhog Messages",
    "-------------------------------------",
    "035. Murli Series",
    "01. Amritology",
    "02. Enchanted Murli",
    "03. Weekly Wisdom",
    "04. Diamond Dadi",
    "05. Avatar",
    "06. Seeing in Being",
    "-------------------------------------",
    "040. News",
    "040. News",
    "----------------------------------------------",
    "041. BK Database",
    "01. Introduction to Brahmakumari",
    "02. BK Centers",
    "03. BK Institutes",
    "04. BK Doctors Phone Numbers",
    "05. All Wings Phone Numbers",
    "06. Suraj Bhai Phone Numbers",
    "07. Madhuban Phone Numbers",
    "08. Biodata of Seniors",
    "09. BK R and D",
    "10. Shanti Stambh Data",
    "11. BK Stores",
    "12. BK DRLUHAR Website Team",
    "13. BK Services",
    "14. BK Advertisement",
    "-------------------------------------",
    "042. Mobile Apps and Software",
    "01. Baba Portal App",
    "02. Mobile Murli App",
    "03. Traffic Control App",
    "04. Mobile Ring Tones",
    "05. Caller Tunes",
    "-------------------------------------",
    "043. Baba Portal",
    "043. Baba Portal",
    "-------------------------------------",
    "045. Hamari Rajdhani Projects",
    "01. Digital Brahmakumari Projects",
    "02. Hamari Rajdhani Projects",
    "03. Pictorial View of Yagna",
    "04. BK Drluhar Website Projects",
    "-------------------------------------",
    "046. Book Your Home at BK City",
    "046. GGRC BK City Ahmedabad",
    "----------------------------------------------",
    "047. Kids Section",
    "047. Kids Section",
    "----------------------------------------------",
    "050. Festivals and Days",
    "01. Indian Festivals",
    "02. Indian and World Days",
    "03. BK Remembrance Days",
    "----------------------------------------------",
    "051. Magazines",
    "051. Magazines",
    "----------------------------------------------",
    "000. Hindi Popular Classes",
    "180. Suraj Bhai",
    "170. Sachin Bhai",
    "301. Shivani Bahen",
    "--------------------- ",
    "052. Books",
    "01. Books",
    "02. Spark Books",
    "03. Audio Books",
    "04. Htm Books",
    "----------------------------------------------",
    "053. Pdf Articles",
    "01. Pdf Articles",
    "02. BK Anilkumar Articles",
    "03. Yogi Khem Pdfs",
    "04. Chakras Pdf",
    "05. Swaman and Titles",
    "----------------------------------------------",
    "054. Ppts",
    "054. PPTs",
    "----------------------------------------------",
    "055. Charts",
    "01. Monthly Charts",
    "02. General Charts",
    "03. Steps and Points",
    "04. Other Charts",
    "----------------------------------------------",
    "056. Dictionaries",
    "01. Dictionaries",
    "02. Murli Shabdkosh",
    "03. Murli Word Search",
    "04. Murli Phrases and Proverbs",
    "----------------------------------------------",
    "057. Drama - Nataks",
    "057. Dramas - Nataks",
    "----------------------------------------------",
    "058. Poems",
    "058. Poems",
    "----------------------------------------------",
    "061. Yagna Graphics and Photos",
    "01. Baba & Mamma",
    "02. Seva",
    "03. Seniors",
    "04. Angels",
    "05. Charts",
    "06. Exhibitions",
    "07. Shiva",
    "08. Yagya History",
    "09. Yagya Buildings",
    "10. GIF",
    "11. Logos",
    "12. Slogan Templates",
    "13. Templates",
    "14. Camera Photos",
    "15. Samshaan Photos",
    "21. Others Photos",
    "----------------------------------------------",
    "062. Other Photos",
    "01. Photos",
    "02. Wallpapers",
    "03. Visual Pdf Photos",
    "04. Pamphlets",
    "05. Calendars",
    "06. Cartoons",
    "07. Shiv Sandesh",
    "----------------------------------------------",
    "063. Recipes",
    "01. Recipes",
    "02. Cooking Videos",
    "03. Cookpad",
    "04. Snacks   ",
    "05. Toli Recipe",
    "06. Spiritualize your Rasoi",
    "----------------------------------------------",
    "071. Audio Section",
    "01. Baba Milan Songs",
    "02. PMTV Hit Songs",
    "03. Hindi Audio Volumes",
    "04. Hindi Audio CDs",
    "05. Hindi New Songs",
    "06. Murli Songs",
    "07. Murli Songs- Amulya Ratan",
    "08. Traffic Control Songs",
    "09. Karaoke Music",
    "10. Bhog Songs",
    "11. Birthday Songs",
    "12. BK Brother and Sisters Songs",
    "13. Non Stop Songs",
    "14. English Songs",
    "15. English Audio CDs",
    "----------------------------------------------",
    "072. Video Section",
    "01. Video Album Songs",
    "02. God of Gods Hindi Movie Songs",
    "03. Todays Video",
    "04. One Minute Mediation Video",
    "05. Flash Video",
    "06. Cartoons Animations Videos",
    "07. Synopsis Video",
    "08. Other Mp4 Classes",
    "----------------------------------------------",
    "073. Documentaries & Tele Films",
    "01. Documentaries & Tele Films",
    "02. Functions Videos",
    "----------------------------------------------",
    "074. Series",
    "01. Aavahan",
    "02. Gyan Darshan",
    "03. Gyan Yagna",
    "04. Khushnuma Jeevan",
    "05. Kumaris Speech",
    "06. Manmanabhav",
    "07. Margdarshan",
    "08. Naritva Darshan",
    "09. Nayi Soch Naya Vishwas",
    "10. Om Museum Shantivan",
    "11. One God One world",
    "12. Preranas - Inspirations by Didis",
    "13. Problems Ko Bye, Happiness Ko",
    "14. Rejuvenate Life",
    "15. Release Your Wings",
    "17. Sampurnata Teevra Purusharth",
    "18. Social Justice Empowerment",
    "19. Solah Kala Sampoorn",
    "20. Sukh Shanti Samrudhee",
    "21. Wisdom Versions",
    "22. Yeh Nasha Ek Sazaa Hai",
    "23. Yog Rahashya",
    "24. Q and A by Dadi Janki",
    "25. Sampurnata Purusharth",
    "----------------------------------------------",
    "075. Stories",
    "01. Stories",
    "02. Moral Stories",
    "03. Tatva Bodh Story",
    "----------------------------------------------",
    "076. 076. Experiences of BKs",
    "076. Experiences of BKs",
    "----------------------------------------------",
    "081. Wings",
    "00. All Wings Introductions",
    "01. Administrators Wing",
    "02. Business & Industry Wing",
    "03. Art and Cultural Wing",
    "04. Education Wing",
    "05. Jurists Wing",
    "06. Medical Wing",
    "07. Media Wing",
    "08. Religious Wing",
    "09. Politicians Services Wing",
    "10. Rural Wing",
    "11. Scientists & Engineers Wing",
    "12. Security Services Wing",
    "13. Social Wing",
    "14. Sports Wing",
    "15. Transport Wing",
    "16. Women Wing",
    "17. Youth Wing",
    "18. Sparc Wing",
    "19. Shipping Aviation and Tourism",
    "20. IT Wing",
    "----------------------------------------------",
    "082. Conferences and Retreats",
    "01. Future of Power Conferences",
    "02. Peace of Mind Conferences",
    "03. Retreats",
    "04. Spirituality in IT - Conferences",
    "05. Other Programs & Conferences",
    "----------------------------------------------",
    "083. Health",
    "01. Depression",
    "02. Stress Management",
    "03. Sleep Management",
    "04. Vyasan - Addiction Mukti",
    "05. BP and Heart Care",
    "06. Diabetes",
    "07. Kidneys",
    "08. Exercise",
    "09. Virtual Baby",
    "10. Divine Garbh Sanskars",
    "11. Food Safety",
    "---------------------------------------------",
    "100. Baba, Mamma and Adi Dev",
    "101. Brahma Baba",
    "102. Mamma Jagdamba",
    "103. Yagna History",
    "104. Adi Dev",
    "105. Dadi Shanta Mani",
    "106. Dadi Chandra Mani",
    "107. Dadi Manohar Indra",
    "108. Dadi Nirmal Shanta",
    "109. Didi Manmohini",
    "110. Dada Vishwaratan",
    "111. Dada Narayan",
    "112. Dada Chandrahas",
    "113. Dada Ratan - London",
    "121. Dadi Prakash Mani",
    "122. Dadi Janki",
    "123. Dadi Guljar",
    "124. Dadi Ratan Mohini",
    "----------------------------------------------",
    "130. Doctors",
    "131. Dr Satish Gupta",
    "132. Dr Girish Patel",
    "133. Dr Prem Masand",
    "134. Dr Shrimant Shahoo",
    "135. Dr Pratap Midha",
    "136. Dr Mohit Gupta",
    "137. Dr Avdesh Sharma",
    "138. Dr Sachin Parab",
    "139. Dr Nikhil Patel",
    "140. Dr R. P. Gupta",
    "151. Dr Jamila Bahen",
    "152. Dr Shubhada Neel",
    "153. Dr Heena",
    "170. Dr Sachin Bhai",
    "----------------------------------------------",
    "160. Professors Classes",
    "161. Prof Swami Nathan",
    "162. Prof E. V. Girish",
    "163. Prof Onkar Chand",
    "164. Prof Chandra Shekhar",
    "----------------------------------------------",
    "170. Brothers Classes",
    "171. Jagdish Bhai",
    "172. Ramesh Bhai",
    "173. Nirwair Bhai",
    "174. Mohan Singhal Bhai",
    "175. Brij Mohan Bhai",
    "177. Karuna Bhai",
    "178. Ramnath Bhai",
    "179. Raju Bhai",
    "180. Suraj Bhai",
    "182. Atam Prakash Bhai - Toli Dept",
    "183. Atam Prakash Bhai - GA",
    "184. Amirchand Bhai",
    "185. Dr Banarasi Bhai",
    "186. Mruthyunjay Bhai",
    "187. Bhagwan Bhai",
    "188. Ram Lochan Bhai",
    "----------------------------------------------",
    "200. Other Brothers Classes",
    "201. Arjun Bhai",
    "202. Ashok Gaba Bhai",
    "203. Avinash Bhai",
    "204. Balram Bhai",
    "205. Basvraj Bhai",
    "206. Bharat Bhusan Bhai",
    "207. Commander Shiv Singh",
    "208. BK Parshuram Bhai",
    "209. Chetan Bhai",
    "210. Chhotelal Bhai",
    "211. Dashrath Bhai",
    "212. Dinesh Bhai",
    "213. Dr Jitendra Shah Bhai",
    "214. Dr Surya Sripada Bhai",
    "215. Dushyant Modi Bhai",
    "216. Gaurav Bhai",
    "217. BK Hemant Bhai",
    "218. Jagbir Bhai",
    "219. Kamal Nath Bhai",
    "220. Bala Kishor Bhai",
    "221. Lalit Bhai",
    "222. Mukesh Bhai - Jaipur",
    "223. Nijar Juma Bhai",
    "224. Nitin Bhai",
    "225. Piyush Bhai",
    "226. Prem Singh Bhai",
    "227. Rajesh Arora Bhai",
    "228. Rajiv Gupta Bhai",
    "229. Ram Prakash Bhai",
    "230. Ramchander Bhai",
    "231. Roshan Bhai",
    "232. Rupesh Bhai",
    "233. Satish Bhai - Singer",
    "234. Shakiraj Singh Bhai",
    "235. Subhash Bhai",
    "236. Yogesh Bhai",
    "239. Babulal Bhai",
    "240. Dr Uday Ranade",
    "241. Sathyanarayana Raju",
    "242. BK Vinod Bhai",
    "243. BK Santram",
    "244. BK Anil Kumar",
    "299. Other Brothers",
    "----------------------------------------------",
    "300. Sisters Classes",
    "301. Shivani Bahen",
    "302. Usha Bahen",
    "303. Sheilu Bahen",
    "304. Geeta Bahen",
    "305. Jayanti Bahen",
    "306. Mohini Bahen",
    "307. Nalini Didi",
    "308. Dr. Nirmala Didi",
    "309. Sudesh Bahen",
    "310. Asha Didi - Delhi",
    "311. Chakradhari Bahen",
    "312. Dr. Savita Bahen",
    "313. Meera Bahen",
    "314. Raj Bahen - Nepal",
    "315. Rajni Bahen - Japan",
    "316. Santosh Bahen",
    "317. Sharda Bahen - Ahmedabad",
    "318. Vedanti Bahen",
    "399. Other Bahens",
    "----------------------------------------------",
    "400. Other Sisters",
    "401. Aarti Bahen",
    "402. Aditi Bahen",
    "403. Aditi Bahen - Bangalore",
    "404. Ambika Bahen",
    "405. Anita Bahen",
    "406. Anjali Bahen",
    "407. Asha Bahen - Khanpur",
    "408. Asmita Bahen",
    "409. Avdhesh Bahen",
    "410. Beena Bahen",
    "411. Bharti Bahen",
    "412. Bhavna Bahen",
    "413. Binny Bahen",
    "414. Champa Bahen",
    "415. Chanda Bahen",
    "416. Chandrakala Bahen",
    "417. Chandrani Bahen",
    "418. Chandrika Bahen",
    "419. Chandru Bahen",
    "420. Deepa Bahen",
    "421. Deepti Bahen",
    "422. Divya Bahen",
    "423. Gayatri Bahen",
    "424. Geeta Bahen - Bhinmal",
    "425. Geeta Bahen - Bilaspur",
    "426. Geeta Bahen - Gyan Sarovar",
    "427. Geeta Bahen - Indore",
    "428. Heena Bahen",
    "429. Hemlata Bahen",
    "430. Indira Bahen",
    "431. Indra Bahen",
    "432. Jasu Bahen",
    "433. Jayanti Bahen - Indore -",
    "434. Jyostna Bahen",
    "435. Kala Bahen",
    "436. Kalpana Bahen",
    "437. Kamla Bahen",
    "438. Kamlesh Bahen",
    "439. Kanan Bahen",
    "440. Kanchan Bahen",
    "441. Kavita Bahen",
    "442. Khyati Bahen",
    "443. Kreena Bahen",
    "444. Kumud Bahen",
    "445. Kunthi Bahen",
    "446. Kusum Bahen",
    "447. Laj Bahen",
    "448. Laxmi Bahen",
    "449. Leena Bahen",
    "450. Madhuri Bahen",
    "451. Mamta Bahen - Mandla",
    "452. Mani Bahen",
    "453. Manisha Bahen",
    "454. Manju Bahen",
    "455. Manorama Bahen",
    "456. Meena Bahen",
    "457. Meena Bahen - UP -",
    "458. Meenakshi Bahen",
    "459. Mohini Bahen - Ganganagar",
    "460. Neena Bahen",
    "461. Nilam Bahen",
    "462. Niranjana Bahen",
    "463. Nirija Bahen",
    "464. Nirupama Bahen",
    "465. Parvati Bahen",
    "466. Pavitra Bahen",
    "467. Pholla Bahen",
    "468. Poonam Bahen",
    "469. Prabha Mishra Bahen",
    "470. Prachi Bahen",
    "471. Prem Bahen",
    "472. Pushpa Bahen",
    "473. Radha Bahen - Lucknow",
    "474. Radhika Bahen",
    "475. Rajkumari Bahen",
    "476. Rama Bahen - Kanpur",
    "477. Rani Bahen",
    "478. Ranjan Bahen - Valsad",
    "479. Ranjna Bahen",
    "480. Ravikala Bahen",
    "481. Rekha Bahen",
    "482. Rukmani Bahen",
    "483. Rupa Bahen",
    "484. Sangeeta Bahen",
    "485. Sapna Bahen",
    "486. Sarita Bahen",
    "488. Saroj Bahen",
    "489. Sashi Bahen",
    "490. Savitri Bahen",
    "491. Seema Bahen - ORC",
    "492. Shanti Bahen",
    "493. Shashi Bahen",
    "494. Sheetal Bahen",
    "495. Shipla Bahen",
    "496. Shobha Bahen",
    "497. Shreya Bahen",
    "498. Shukla Bahen",
    "499. Sita Bahen",
    "500. Sneha Bahen",
    "501. Somprabha Bahen",
    "502. Sona Bahen",
    "503. Sudha Bahen",
    "504. Sujata Bahen",
    "505. Suman Bahen",
    "506. Sunanda Bahen",
    "507. Sundari Bahen",
    "508. Sunita Bahen",
    "509. Sushma Bahen",
    "510. Urmil Bahen",
    "511. Urmila Bahen",
    "512. Usha Bahen - Ujjain",
    "513. Vandana Bahen",
    "514. Veena Bahen",
    "515. Vidya Bahen - Kanpur",
    "516. Vijay Bahen",
    "517. Vimla Bahen",
    "518. Yogini Bahen",
    "599. Other Bahens",
    "----------------------------------------------",
    "600. Foreign Sisters",
    "601. Sister Alice",
    "602. Sister Anna",
    "603. Sister Aruna",
    "604. Sister Awatif",
    "605. Sister Becky",
    "606. Sister Bhavan - New Zeland",
    "607. Sister Blinda",
    "608. Sister Carmen",
    "609. Sister Carolyn",
    "610. Sister Denise",
    "611. Sister Diane",
    "612. Sister Dr Kumud",
    "613. Sister Gopi",
    "614. Sister Guddi",
    "615. Sister Helena",
    "616. Sister Jacqueline",
    "617. Sister Jaina",
    "618. Sister Janki - Bali Indonesia",
    "619. Sister Judi",
    "620. Sister Justine",
    "621. Sister Luciana",
    "622. Sister Manda",
    "623. Sister Mathilde",
    "624. Sister Maureen",
    "625. Sister Morni",
    "626. Sister Niti Bahen",
    "627. Sister Pari Gulmohor",
    "628. Sister Philippa",
    "629. Sister Rosemary",
    "630. Sister Sally",
    "631. Sister Sharona",
    "632. Sister Shreen Tempa",
    "633. Sister Waddy",
    "699. Other Sisters",
    "----------------------------------------------",
    "700. Foreign Brothers",
    "701. Brother Anthony",
    "702. Brother Charlie",
    "703. Brother David",
    "704. Brother Deepak Chopra",
    "705. Brother Denzal",
    "706. Brother Doctor Nasim",
    "707. Brother Ed",
    "708. Brother Eric",
    "701. Brother Golo",
    "710. Brother Gopal",
    "713. Brother Ken O'Donnell - Brazil",
    "714. Brother Lee",
    "715. Brother Marcello",
    "716. Brother Mathew",
    "717. Brother Mike George",
    "718. Brother Neville Hodgkinson",
    "719. Brother Perkins",
    "720. Brother Shanti Krishna",
    "721. Brother Stephan",
    "722. Brother Tony",
    "723. Brother Vijay",
    "799. Other Brothers",
    "----------------------------------------------",
    "900. Indian Languages",
    "901. English",
    "902. Tamil",
    "903. Telugu",
    "904. Kannada",
    "905. Malayalam",
    "906. Bengali",
    "907. Assamese",
    "908. Odiya",
    "909. Punjabi",
    "910. Marathi",
    "911. Gujarati",
    "912. Sindhi",
    "913. Mizo",
    "914. Urdu",
    "----------------------------------------------",
    "930. Foreign Languages",
    "931. Nepali",
    "932. Deutsch",
    "933. Spanish",
    "934. Italian",
    "935. Chinese",
    "936. Tamil-Lanka",
    "937. French",
    "938. Greek",
    "939. Hungarian",
    "940. Korean",
    "941. Polish",
    "942. Portuguese",
    "943. Thai",
    "944. Sinhala",
    "----------------------------------------------",
  );

?>